# Generated by Django 3.0.2 on 2020-01-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(max_length=10)),
                ('dob', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('pin', models.IntegerField(max_length=100)),
                ('pname', models.CharField(max_length=100)),
                ('prelation', models.CharField(max_length=100)),
                ('pmob', models.IntegerField(max_length=10)),
                ('p2name', models.CharField(max_length=100)),
                ('p2relation', models.CharField(max_length=100)),
                ('p2mob', models.IntegerField(max_length=10)),
                ('latitude', models.FloatField(max_length=20)),
                ('longitude', models.FloatField(max_length=20)),
            ],
        ),
    ]
