# Generated by Django 3.0.2 on 2020-01-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20200120_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
