# Generated by Django 3.0.2 on 2020-01-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20200120_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
