# Generated by Django 3.0.2 on 2020-01-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_auto_20200120_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='intimate_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=6)),
                ('pname', models.CharField(max_length=100)),
                ('prelation', models.CharField(max_length=100)),
                ('pmob', models.CharField(max_length=10)),
                ('p2name', models.CharField(max_length=100)),
                ('p2relation', models.CharField(max_length=100)),
                ('p2mob', models.CharField(max_length=10)),
                ('latitude', models.FloatField(max_length=20)),
                ('longitude', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='report_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=6)),
                ('pname', models.CharField(max_length=100)),
                ('prelation', models.CharField(max_length=100)),
                ('pmob', models.CharField(max_length=10)),
                ('p2name', models.CharField(max_length=100)),
                ('p2relation', models.CharField(max_length=100)),
                ('p2mob', models.CharField(max_length=10)),
                ('latitude', models.FloatField(max_length=20)),
                ('longitude', models.FloatField(max_length=20)),
                ('details', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='information',
            new_name='emergency_information',
        ),
    ]
