# Generated by Django 3.0.2 on 2020-02-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20200131_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency_information',
            name='area',
        ),
        migrations.RemoveField(
            model_name='emergency_information',
            name='district',
        ),
        migrations.RemoveField(
            model_name='emergency_information',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='intimate_information',
            name='area',
        ),
        migrations.RemoveField(
            model_name='intimate_information',
            name='district',
        ),
        migrations.RemoveField(
            model_name='intimate_information',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='report_information',
            name='details',
        ),
        migrations.AddField(
            model_name='emergency_information',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='intimate_information',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='report_information',
            name='report',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
