from django.db import models

# Create your models here.
class intimate_information(models.Model):
    username=models.CharField(max_length=100)
    mobile=models.CharField(max_length=10)
    dob=models.CharField(max_length=100)
    address=models.CharField(max_length=300,null=True)
    pname=models.CharField(max_length=100)
    prelation=models.CharField(max_length=100)
    pmob=models.CharField(max_length=10)
    p2name = models.CharField(max_length=100)
    p2relation = models.CharField(max_length=100)
    p2mob = models.CharField(max_length=10)
    latitude=models.FloatField(max_length=20)
    longitude=models.FloatField(max_length=20)
class report_information(models.Model):
    username=models.CharField(max_length=100)
    mobile=models.CharField(max_length=10)
    dob=models.CharField(max_length=100)
    district=models.CharField(max_length=100)
    area = models.CharField(max_length=100)
    pin= models.CharField(max_length=6)
    pname=models.CharField(max_length=100)
    prelation=models.CharField(max_length=100)
    pmob=models.CharField(max_length=10)
    p2name = models.CharField(max_length=100)
    p2relation = models.CharField(max_length=100)
    p2mob = models.CharField(max_length=10)
    latitude=models.FloatField(max_length=20)
    longitude=models.FloatField(max_length=20)
    report=models.TextField(max_length=1000,null=True)
class emergency_information(models.Model):
    username = models.CharField(max_length=100)
    mobile = models.CharField(max_length=10)
    dob = models.CharField(max_length=100)
    address = models.CharField(max_length=300,null=True)
    pname = models.CharField(max_length=100)
    prelation = models.CharField(max_length=100)
    pmob = models.CharField(max_length=10)
    p2name = models.CharField(max_length=100)
    p2relation = models.CharField(max_length=100)
    p2mob = models.CharField(max_length=10)
    latitude = models.FloatField(max_length=20)
    longitude = models.FloatField(max_length=20)
