# Generated by Django 3.0.2 on 2020-01-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police_login',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='police_login',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
