# Generated by Django 3.0.2 on 2020-02-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_login', '0002_auto_20200119_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_login',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='police_login',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='police_login',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='police_login',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
